In [ ]:
import pandas as pd
import numpy as np
from magi_module_Copy import get_report
import matplotlib.pyplot as plt
from datetime import datetime
from pykrx import stock
%matplotlib inline

In [ ]:
etf_info = pd.read_csv('./../TIGER ETF기반 투자전략 개발 과제 다운로드/data/etf_info.csv', encoding = 'euc_kr')
etf_info.head()

## pykrx패키지로 괴리율 구하기

In [8]:
etfcode = etf_info['코드'].astype('str')
list(etfcode)

['A377990',
 'A376410',
 'A364960',
 'A364980',
 'A364970',
 'A365000',
 'A364990',
 'A365040',
 'A315270',
 'A310970',
 'A310960',
 'A307510',
 'A307520',
 'A305540',
 'A300610',
 'A292150',
 'A292160',
 'A289260',
 'A289250',
 'A277630',
 'A277650',
 'A277640',
 'A261140',
 'A261060',
 'A261070',
 'A252000',
 'A232080',
 'A228820',
 'A228810',
 'A228790',
 'A228800',
 'A227540',
 'A227560',
 'A227550',
 'A227570',
 'A217790',
 'A211560',
 'A210780',
 'A174350',
 'A157490',
 'A157500',
 'A150460',
 'A147970',
 'A143860',
 'A139260',
 'A139280',
 'A139250',
 'A139270',
 'A139220',
 'A139230',
 'A139290',
 'A139240',
 'A138540',
 'A138530',
 'A138520',
 'A102110',
 'A098560',
 'A091230',
 'A091220',
 'A387270',
 'A387280',
 'A381170',
 'A381180',
 'A371160',
 'A371460',
 'A371470',
 'A371450',
 'A360750',
 'A357870',
 'A341850',
 'A329750',
 'A329200',
 'A319640',
 'A305080',
 'A302190',
 'A292560',
 'A289480',
 'A276000',
 'A275980',
 'A272580',
 'A269370',
 'A248270',
 'A248260',
 'A245340',
 'A245350',
 'A245360',
 'A241180',
 'A237440',
 'A203780',
 'A195930',
 'A195920',
 'A182490',
 'A192090',
 'A182480',
 'A160580',
 'A166400',
 'A157450',
 'A143850',
 'A139320',
 'A139310',
 'A137610',
 'A133690',
 'A130680',
 'A117690',
 'A114820',
 'A105010',
 'A217770',
 'A302170',
 'A302180',
 'A243880',
 'A243890',
 'A233160',
 'A252710',
 'A267770',
 'A123310',
 'A250780',
 'A123320',
 'A204480',
 'A225040',
 'A217780',
 'A236350',
 'A225050',
 'A261120',
 'A225030',
 'A225060',
 'A261110',
 'A387270']

In [9]:
A = 'A'
etfnoA = []
for i in range(len(etfcode)):
    a = ''.join(x for x in etfcode[i] if x not in A)
    etfnoA.append(a)
etfnoA

['377990',
 '376410',
 '364960',
 '364980',
 '364970',
 '365000',
 '364990',
 '365040',
 '315270',
 '310970',
 '310960',
 '307510',
 '307520',
 '305540',
 '300610',
 '292150',
 '292160',
 '289260',
 '289250',
 '277630',
 '277650',
 '277640',
 '261140',
 '261060',
 '261070',
 '252000',
 '232080',
 '228820',
 '228810',
 '228790',
 '228800',
 '227540',
 '227560',
 '227550',
 '227570',
 '217790',
 '211560',
 '210780',
 '174350',
 '157490',
 '157500',
 '150460',
 '147970',
 '143860',
 '139260',
 '139280',
 '139250',
 '139270',
 '139220',
 '139230',
 '139290',
 '139240',
 '138540',
 '138530',
 '138520',
 '102110',
 '098560',
 '091230',
 '091220',
 '387270',
 '387280',
 '381170',
 '381180',
 '371160',
 '371460',
 '371470',
 '371450',
 '360750',
 '357870',
 '341850',
 '329750',
 '329200',
 '319640',
 '305080',
 '302190',
 '292560',
 '289480',
 '276000',
 '275980',
 '272580',
 '269370',
 '248270',
 '248260',
 '245340',
 '245350',
 '245360',
 '241180',
 '237440',
 '203780',
 '195930',
 '195920',
 '182490',
 '192090',
 '182480',
 '160580',
 '166400',
 '157450',
 '143850',
 '139320',
 '139310',
 '137610',
 '133690',
 '130680',
 '117690',
 '114820',
 '105010',
 '217770',
 '302170',
 '302180',
 '243880',
 '243890',
 '233160',
 '252710',
 '267770',
 '123310',
 '250780',
 '123320',
 '204480',
 '225040',
 '217780',
 '236350',
 '225050',
 '261120',
 '225030',
 '225060',
 '261110',
 '387270']

In [12]:
error = []
price_deviation = stock.get_etf_price_deviation("20060101", "20210531", etfnoA[0])[['괴리율']].reset_index()
for i in range(1,len(etfnoA)):
    try:
        df = stock.get_etf_price_deviation("20060101", "20210531", etfnoA[i])
        price_deviation_i = df[['괴리율']].reset_index()
        price_deviation = pd.merge(price_deviation, price_deviation_i, how='outer', on='날짜', sort=True)

    except:
        error.append(etfnoA[i])
        pass
price_deviation.columns = ['tdate']+ list(etfcode)
print(price_deviation)
print(error)

          tdate  A377990  A376410  A364960  A364980  A364970  A365000  \
0    2006-06-27      NaN      NaN      NaN      NaN      NaN      NaN
1    2006-06-28      NaN      NaN      NaN      NaN      NaN      NaN
2    2006-06-29      NaN      NaN      NaN      NaN      NaN      NaN
3    2006-06-30      NaN      NaN      NaN      NaN      NaN      NaN
4    2006-07-03      NaN      NaN      NaN      NaN      NaN      NaN
...         ...      ...      ...      ...      ...      ...      ...
3684 2021-05-25    -0.13    -0.27    -0.46    -0.33    -0.41    -0.28
3685 2021-05-26    -0.12    -0.32    -0.33    -0.22    -0.22    -0.32
3686 2021-05-27    -0.25    -0.04    -0.17     0.08    -0.33    -0.25
3687 2021-05-28     0.00    -0.05    -0.28    -0.20     0.01    -0.40
3688 2021-05-31    -0.33    -0.13    -0.25    -0.08    -0.13    -0.30

      A364990  A365040  A315270  ...  A204480  A225040  A217780  A236350  \
0         NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
1         NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
2         NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
3         NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
4         NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
...       ...      ...      ...  ...      ...      ...      ...      ...
3684    -0.06    -0.44    -0.47  ...     5.28     0.66    -2.15     0.74
3685    -0.02    -0.09     0.01  ...    -0.58     0.40     0.71     0.76
3686     0.11     0.02    -0.06  ...    -0.20    -0.16     0.47     0.44
3687    -0.05     0.03    -0.32  ...    -2.04     0.20     0.86     0.90
3688    -0.00    -0.27    -0.39  ...    -0.57     0.21     0.45     1.27

      A225050  A261120  A225030  A225060  A261110  A387270
0         NaN      NaN      NaN      NaN      NaN      NaN
1         NaN      NaN      NaN      NaN      NaN      NaN
2         NaN      NaN      NaN      NaN      NaN      NaN
3         NaN      NaN      NaN      NaN      NaN      NaN
4         NaN      NaN      NaN      NaN      NaN      NaN
...       ...      ...      ...      ...      ...      ...
3684     0.47    -0.14    -0.34     1.90     0.19     0.65
3685     0.43    -0.59    -0.15     1.08     0.02     0.16
3686     0.15     0.12     0.02    -0.11    -0.18    -0.14
3687     0.09    -0.15    -0.21     0.30     0.19    -0.25
3688    -0.34    -0.15    -0.10     1.30     0.11    -0.22

[3689 rows x 128 columns]
[]

In [27]:
price_deviation = pd.concat([price_deviation[['tdate']], price_deviation[price_deviation.columns.difference(['tdate'])].mul(-1)], axis=1)

In [29]:
price_deviation.to_csv('./price_deviation.csv')

In [30]:
price_deviation['tdate']

0      2006-06-27
1      2006-06-28
2      2006-06-29
3      2006-06-30
4      2006-07-03
          ...
3684   2021-05-25
3685   2021-05-26
3686   2021-05-27
3687   2021-05-28
3688   2021-05-31
Name: tdate, Length: 3689, dtype: datetime64[ns]

#### 스코어가 높다 = 괴리율이 높다 = (NAV < 현재가격) : ETF의 현재가격은 NAV를 따를 것이기 때문에 **가격하락** 예상. --> **매도해야**  
#### 스코어가 낮다 = 괴리율이 낮다 = (NAV > 현재가격) : ETF의 현재가격은 NAV를 따를 것이기 때문에 **가격상승** 예상. --> **매수해야**

#### 그래서 스코어에 - 붙임!